name: listview_example_01
description: "A Flutter demo app showcasing the ListView widget with multiple Containers and styled Text, demonstrating scrollable vertical lists with custom colors."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
