name: sliverappbar_example_02
description: "A Flutter demo app showcasing SliverAppBar with stretch behavior, overscroll trigger, and dynamic toggle control."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
