name: layout_single_widget_container_example_01
description: "A Flutter demo app showcasing how to lay out a single widget using Container, applying padding and displaying a custom BorderedImage with border and rounded corners."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
