name: appbar_example_01
description: "This sample shows an AppBar with two simple actions. The first action opens a SnackBar, while the second action navigates to a new page."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
