name: platform_device_specs
description: "A Flutter playground app that displays platform and device specifications using MediaQuery, Theme.of(context).platform, and the dart:io Platform class, with web detection via kIsWeb."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
