name: flutter_application_02
description: "This simple Flutter app demonstrates basic UI structure and interactivity. It features a home screen with an AppBar titled 'Home App Example' and a centered ElevatedButton. The button responds to short and long presses by printing messages to the console. The app showcases core Flutter widgets including MaterialApp, Scaffold, AppBar, and ElevatedButton, along with custom text styling."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
