name: flutter_application_13
description: "A Flutter multi-page demo app (flutter_application_13) featuring a Fitness Tracker with workout stats and a Developer Portfolio with skills and experience, using custom widgets and dynamic lists."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
