name: listview_example_07
description: "A Flutter demo app showcasing item selection in ListView and GridView, with support for selection mode, select all/unselect all, and toggling between list and grid layouts."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
