name: flexible_example_04
description: "A Flutter demo app comparing Flexible with loose vs tight fit, Expanded, and fixed-size widgets to illustrate space distribution in a Column."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
