name: yt_cors_proxy
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.5.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
