name: sliverappbar_example_03
description: "A Flutter demo app showcasing SliverAppBar with interactive pinned, floating, and snap properties."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
