name: flutter_application_12
description: "A Flutter multi-page demo app (flutter_application_12) showcasing AlertDialog, Stack layouts, CustomPainter drawing, and reusable widgets with navigation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
