name: layout_multiple_widgets_row_column_example
description: "A Flutter demo app showcasing how to combine Row and Column widgets to arrange multiple widgets horizontally and vertically, using custom BorderedImage widgets with labels."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
