name: layout_single_widget_container_example_02
description: "A Flutter demo app showcasing how to combine Center and Container to lay out a single widget with padding, alignment, and a custom BorderedImage."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
