name: dropdownmenu_example_01
description: "A Flutter demo app showcasing the DropdownMenu widget with custom enum entries, controllers, filtering, and dynamic selection display."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
