name: text_example_02
description: "Using the Text.rich constructor, the Text widget can display a paragraph with differently styled TextSpans. The sample that follows displays 'Hello beautiful world' with different styles for each word."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
