name: textformfield_example_03
description: "A Flutter demo app showcasing TextFormField with synchronous validation, asynchronous server-side checks, dynamic error handling, and loading state."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
