name: scrolling_widgets_listview_example_02
description: "A Flutter demo app showcasing how to use ListView.builder to display a dynamic list of ToDo items with conditional rendering for completion status."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
