name: floatingactionbutton_example_03
description: "A Flutter demo app showcasing FloatingActionButton styling with different ColorScheme roles: surface, secondary, and tertiary."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
