name: iconbutton_example_04
description: "A Flutter demo app showcasing the different Material 3 IconButton types: standard, filled, filled tonal, and outlined, with enabled and disabled states."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
