name: flutter_application_14
description: "A Flutter demo app showcasing a Wellness Tracker with profile card, activity stats, dynamic activity log, and a form inside a modal bottom sheet to add new activities."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
