name: listview_example_05
description: "A Flutter demo app showcasing the use of shrinkWrap with ListView and CustomScrollView, allowing scrollable widgets to size themselves based on their children."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
