name: center_example
description: "A Flutter demo app showcasing how to lay out a single widget using Center, with a custom BorderedImage widget displaying Dash with a simple border."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
