// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAOYq3kby3PChEsut-Un1ruyxNEQk9Cg',
    appId: '1:645189824102:web:f1fd8ee367b2665ab087a7',
    messagingSenderId: '645189824102',
    projectId: 'huertos-urbanos-6b010',
    authDomain: 'huertos-urbanos-6b010.firebaseapp.com',
    storageBucket: 'huertos-urbanos-6b010.firebasestorage.app',
    measurementId: 'G-SSNVTX3874',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKohF29AibL7uNoIGtyg72gYjLU9KuJN0',
    appId: '1:645189824102:android:103779114835e6a9b087a7',
    messagingSenderId: '645189824102',
    projectId: 'huertos-urbanos-6b010',
    storageBucket: 'huertos-urbanos-6b010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3wbfcS7dIKZMeUgTJR2rbal135AYevP4',
    appId: '1:645189824102:ios:2febd61de4462e19b087a7',
    messagingSenderId: '645189824102',
    projectId: 'huertos-urbanos-6b010',
    storageBucket: 'huertos-urbanos-6b010.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3wbfcS7dIKZMeUgTJR2rbal135AYevP4',
    appId: '1:645189824102:ios:2febd61de4462e19b087a7',
    messagingSenderId: '645189824102',
    projectId: 'huertos-urbanos-6b010',
    storageBucket: 'huertos-urbanos-6b010.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqAOYq3kby3PChEsut-Un1ruyxNEQk9Cg',
    appId: '1:645189824102:web:f31a38aa0019c448b087a7',
    messagingSenderId: '645189824102',
    projectId: 'huertos-urbanos-6b010',
    authDomain: 'huertos-urbanos-6b010.firebaseapp.com',
    storageBucket: 'huertos-urbanos-6b010.firebasestorage.app',
    measurementId: 'G-7F2QGEMEE3',
  );
}
