name: adaptive_app
description: >
  A cross-platform Flutter application built from the official Flutter Adaptive Apps Codelab.
  It demonstrates adaptive layouts, platform detection, and Google authentication across
  Android, iOS, Web, Windows, macOS, and Linux.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  go_router: ^16.2.5
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  logging: ^1.3.0
  provider: ^6.1.5+1
  split_view: ^3.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
